window.produtos = [
// Bebidas
{ nome: "Fanta Uva Lata", categoria: "Refrigerante" },
{ nome: "Fanta Uva 600ml", categoria: "Refrigerante" },
{ nome: "Fanta Uva 2L", categoria: "Refrigerante" },
{ nome: "Fanta Uva KS", categoria: "Refrigerante" },
{ nome: "Fanta Laranja Lata", categoria: "Refrigerante" },
{ nome: "Fanta Laranja 600ml", categoria: "Refrigerante" },
{ nome: "Fanta Laranja 2L", categoria: "Refrigerante" },
{ nome: "Fanta Laranja KS", categoria: "Refrigerante" },
{ nome: "Coca-Cola Normal KS", categoria: "Refrigerante" },
{ nome: "Coca-Cola Normal 600ml", categoria: "Refrigerante" },
{ nome: "Coca-Cola Normal 2L", categoria: "Refrigerante" },
{ nome: "Coca-Cola Zero KS", categoria: "Refrigerante" },
{ nome: "Coca-Cola Zero 600ml", categoria: "Refrigerante" },
{ nome: "Coca-Cola Zero 2L", categoria: "Refrigerante" },
{ nome: "Schweppes Lata", categoria: "Refrigerante" },
{ nome: "Schweppes Tônica", categoria: "Refrigerante" },
{ nome: "Schweppes Citrus", categoria: "Refrigerante" },
{ nome: "Schweppes Citrus Zero", categoria: "Refrigerante" },
{ nome: "Sprite Lata", categoria: "Refrigerante" },
{ nome: "Sprite 500ml", categoria: "Refrigerante" },
{ nome: "Sprite 2L", categoria: "Refrigerante" },
{ nome: "Sprite KS", categoria: "Refrigerante" },
{ nome: "Guaraná Lata", categoria: "Refrigerante" },
{ nome: "Guaraná 2L", categoria: "Refrigerante" },
{ nome: "Itubaína Lata", categoria: "Refrigerante" },
{ nome: "Itubaína KS", categoria: "Refrigerante" },
{ nome: "Itubaína 600ml", categoria: "Refrigerante" },
{ nome: "Itubaína 2L", categoria: "Refrigerante" },
{ nome: "Sukita Laranja 2L", categoria: "Refrigerante" },
{ nome: "Sukita Limão 2L", categoria: "Refrigerante" },
{ nome: "Água Sem Gás", categoria: "Refrigerante" },
{ nome: "Água Com Gás", categoria: "Refrigerante" },
{ nome: "H2O Normal", categoria: "Refrigerante" },
{ nome: "H2O Zero", categoria: "Refrigerante" },
{ nome: "Água Tônica Normal", categoria: "Refrigerante" },
{ nome: "Água Tônica Zero", categoria: "Refrigerante" },
{ nome: "Soda Normal 2L", categoria: "Refrigerante" },
{ nome: "Soda Zero 2L", categoria: "Refrigerante" },
{ nome: "Del Valle Goiaba", categoria: "Refrigerante" },
{ nome: "Del Valle Manga", categoria: "Refrigerante" },
{ nome: "Del Valle Maracujá", categoria: "Refrigerante" },
{ nome: "Del Valle Uva", categoria: "Refrigerante" },
{ nome: "Del Valle Pêssego", categoria: "Refrigerante" },
{ nome: "Gatorade", categoria: "Refrigerante" },
{ nome: "Powerade", categoria: "Refrigerante" },
{ nome: "Red Bull Normal", categoria: "Refrigerante" },
{ nome: "Red Bull Tropical", categoria: "Refrigerante" },
{ nome: "Red Bull Melancia", categoria: "Refrigerante" },
{ nome: "Monster Normal", categoria: "Refrigerante" },
{ nome: "Monster Manga", categoria: "Refrigerante" },
{ nome: "Bally 2L", categoria: "Refrigerante" },

// Cervejas
{ nome: "Heineken 600ml", categoria: "Cerveja" },
{ nome: "Heineken KS", categoria: "Cerveja" },
{ nome: "Heineken Lata Normal", categoria: "Cerveja" },
{ nome: "Heineken Lata Zero", categoria: "Cerveja" },
{ nome: "Amstel 600ml", categoria: "Cerveja" },
{ nome: "Amstel KS", categoria: "Cerveja" },
{ nome: "Amstel Ultra", categoria: "Cerveja" },
{ nome: "Amstel Lata Normal", categoria: "Cerveja" },
{ nome: "Amstel Lata Zero", categoria: "Cerveja" },
{ nome: "Skol 600ml", categoria: "Cerveja" },
{ nome: "Skol Barrigudinha", categoria: "Cerveja" },
{ nome: "Skol Lata", categoria: "Cerveja" },
{ nome: "Brahma 600ml", categoria: "Cerveja" },
{ nome: "Brahma Lata", categoria: "Cerveja" },
{ nome: "Estrella Galicia 600ml", categoria: "Cerveja" },
{ nome: "Estrella Galicia Long Neck", categoria: "Cerveja" },
{ nome: "Estrella Galicia Lata Normal", categoria: "Cerveja" },
{ nome: "Estrella Galicia Lata Zero", categoria: "Cerveja" },
{ nome: "Stella Artois Long Neck", categoria: "Cerveja" },
{ nome: "Original 600ml", categoria: "Cerveja" },
{ nome: "Original Barrigudinha", categoria: "Cerveja" },
{ nome: "Original Lata", categoria: "Cerveja" },
{ nome: "Corona 600ml", categoria: "Cerveja" },
{ nome: "Corona Long Neck", categoria: "Cerveja" },
{ nome: "Corona Lata", categoria: "Cerveja" },
{ nome: "Kaiser 600ml", categoria: "Cerveja" },
{ nome: "Spaten 600ml", categoria: "Cerveja" },
{ nome: "Spaten Long Neck", categoria: "Cerveja" },
{ nome: "Itaipava Long Neck Normal", categoria: "Cerveja" },
{ nome: "Itaipava Long Neck Zero", categoria: "Cerveja" },
{ nome: "Itaipava Long Neck Preta", categoria: "Cerveja" },
{ nome: "Itaipava Lata Normal", categoria: "Cerveja" },
{ nome: "Itaipava Lata Zero", categoria: "Cerveja" },
{ nome: "Eisenbahn 600ml Pilsen", categoria: "Cerveja" },
{ nome: "Eisenbahn 600ml Unfiltered", categoria: "Cerveja" },
{ nome: "Eisenbahn Long Neck IPA", categoria: "Cerveja" },
{ nome: "Eisenbahn Long Neck Session", categoria: "Cerveja" },
{ nome: "Eisenbahn Long Neck Pale Ale", categoria: "Cerveja" },
{ nome: "Eisenbahn Long Neck Weizenbier", categoria: "Cerveja" },
{ nome: "Praya Long Neck", categoria: "Cerveja" },
{ nome: "Petra Long Neck", categoria: "Cerveja" },

// Destilados e Ice
{ nome: "Buchanan's", categoria: "Destilado" },
{ nome: "Chivas", categoria: "Destilado" },
{ nome: "Red Label", categoria: "Destilado" },
{ nome: "Jack Daniel's", categoria: "Destilado" },
{ nome: "White Horse", categoria: "Destilado" },
{ nome: "Ballantine's 8 anos", categoria: "Destilado" },
{ nome: "Ballantine's 12 anos", categoria: "Destilado" },
{ nome: "Black Label", categoria: "Destilado" },
{ nome: "Old Parr", categoria: "Destilado" },
{ nome: "Seleta", categoria: "Destilado" },
{ nome: "51", categoria: "Destilado" },
{ nome: "Velho Barreiro", categoria: "Destilado" },
{ nome: "1922", categoria: "Destilado" },
{ nome: "São João da Barra", categoria: "Destilado" },
{ nome: "Salinas", categoria: "Destilado" },
{ nome: "Boazinha", categoria: "Destilado" },
{ nome: "Cabaré", categoria: "Destilado" },
{ nome: "Ypióca", categoria: "Destilado" },
{ nome: "Saideira de Minas", categoria: "Destilado" },
{ nome: "Orizona", categoria: "Destilado" },
{ nome: "Smirnoff", categoria: "Destilado" },
{ nome: "Tanqueray", categoria: "Destilado" },
{ nome: "Gordon's", categoria: "Destilado" },
{ nome: "Intencion", categoria: "Destilado" },
{ nome: "RMS", categoria: "Destilado" },
{ nome: "Aperol", categoria: "Destilado" },
{ nome: "Campari", categoria: "Destilado" },
{ nome: "Dreher", categoria: "Destilado" },
{ nome: "Fernet", categoria: "Destilado" },
{ nome: "Jurubeba", categoria: "Destilado" },
{ nome: "Paratudo", categoria: "Destilado" },
{ nome: "Bacardi", categoria: "Destilado" },
{ nome: "Tequila", categoria: "Destilado" },
{ nome: "Catuaba", categoria: "Destilado" },
{ nome: "Saquê Soft", categoria: "Destilado" },
{ nome: "Eternity Morango", categoria: "Ice/Gin" },
{ nome: "Eternity Maçã", categoria: "Ice/Gin" },
{ nome: "Eternity Melancia", categoria: "Ice/Gin" },
{ nome: "Eternity Tropical", categoria: "Ice/Gin" },
{ nome: "Smirnoff Ice", categoria: "Ice/Gin" },
{ nome: "Beats Melancia", categoria: "Ice/Gin" },
{ nome: "Beats Tropical", categoria: "Ice/Gin" },

// Mercearia
{ nome: "Arroz", categoria: "Mercearia" },
{ nome: "Feijão Carioca", categoria: "Mercearia" },
{ nome: "Feijão Preto", categoria: "Mercearia" },
{ nome: "Açúcar", categoria: "Mercearia" },
{ nome: "Sal", categoria: "Mercearia" },
{ nome: "Sal Grosso", categoria: "Mercearia" },
{ nome: "Farinha de Rosca", categoria: "Mercearia" },
{ nome: "Farinha de Mandioca", categoria: "Mercearia" },
{ nome: "Fubá", categoria: "Mercearia" },
{ nome: "Polenta", categoria: "Mercearia" },
{ nome: "Ervilha", categoria: "Mercearia" },
{ nome: "Milho", categoria: "Mercearia" },
{ nome: "Molho de Tomate", categoria: "Mercearia" },
{ nome: "Mostarda", categoria: "Mercearia" },
{ nome: "Ketchup", categoria: "Mercearia" },
{ nome: "Molho de Pimenta", categoria: "Mercearia" },
{ nome: "Óleo", categoria: "Mercearia" },
{ nome: "Óleo de Algodão", categoria: "Mercearia" },
{ nome: "Azeite de Dendê", categoria: "Mercearia" },
{ nome: "Vinagre", categoria: "Mercearia" },
{ nome: "Leite de Coco", categoria: "Mercearia" },
{ nome: "Azeitona Normal", categoria: "Mercearia" },
{ nome: "Azeitona Fatiada", categoria: "Mercearia" },
{ nome: "Pimenta Biquinho", categoria: "Mercearia" },
{ nome: "Macarrão", categoria: "Mercearia" },
{ nome: "Ovo", categoria: "Mercearia" },
{ nome: "Páprica Doce", categoria: "Mercearia" },
{ nome: "Páprica Defumada", categoria: "Mercearia" },

// Carnes e Congelados
{ nome: "Cupim", categoria: "Carne" },
{ nome: "Costela Bovina", categoria: "Carne" },
{ nome: "Carne Moída", categoria: "Carne" },
{ nome: "Contra Filé", categoria: "Carne" },
{ nome: "Carne Seca", categoria: "Carne" },
{ nome: "Bisteca Bovina", categoria: "Carne" },
{ nome: "Rabada", categoria: "Carne" },
{ nome: "Bacon", categoria: "Carne" },
{ nome: "Calabresa", categoria: "Carne" },
{ nome: "Barriga Suína", categoria: "Carne" },
{ nome: "Pé Suíno", categoria: "Carne" },
{ nome: "Orelha Suína", categoria: "Carne" },
{ nome: "Rabo Suíno", categoria: "Carne" },
{ nome: "Língua Suína", categoria: "Carne" },
{ nome: "Costelinha Suína", categoria: "Carne" },
{ nome: "Coxa Sobrecoxa", categoria: "Carne" },
{ nome: "Peito de Frango", categoria: "Carne" },
{ nome: "Filé de Frango", categoria: "Carne" },
{ nome: "Frango a Passarinho", categoria: "Carne" },
{ nome: "Filé de Coxa", categoria: "Carne" },
{ nome: "Camarão", categoria: "Carne" },
{ nome: "Filé de Merluza", categoria: "Carne" },
{ nome: "Batata Frita Congelada", categoria: "Carne" },
{ nome: "Mandioca Congelada", categoria: "Carne" },

// Limpeza
{ nome: "Papel Toalha", categoria: "Limpeza" },
{ nome: "Guardanapo", categoria: "Limpeza" },
{ nome: "Papel Higiênico", categoria: "Limpeza" },
{ nome: "Canudo", categoria: "Limpeza" },
{ nome: "Saquinho de Talher", categoria: "Limpeza" },
{ nome: "Espeto", categoria: "Limpeza" },
{ nome: "Palito", categoria: "Limpeza" },
{ nome: "Marmita Descartável", categoria: "Limpeza" },
{ nome: "Talher de Plástico", categoria: "Limpeza" },
{ nome: "Copo/Pote com Tampa 145ml", categoria: "Limpeza" },
{ nome: "Pano Perfex", categoria: "Limpeza" },
{ nome: "Pano de Chão", categoria: "Limpeza" },
{ nome: "Luva Descartável", categoria: "Limpeza" },
{ nome: "Touca Descartável", categoria: "Limpeza" },
{ nome: "Bombril", categoria: "Limpeza" },
{ nome: "Esponja", categoria: "Limpeza" },
{ nome: "Álcool", categoria: "Limpeza" }
];